### ISSUE TITLE
lib versioning

### ISSUE THREAD

**Issue by albfan** [albfan/nemiver#7]
As public interface may vary while it is polluted and integrated with gnome-builder, would be better to do versioning on it.

now nemiver is version 0.9.6. Must check how other projects versioning its public interface, because methods change a lot:

Keep only major version:
https://github.com/GNOME/glib/blob/master/configure.ac#L3421

Use templates:
https://github.com/GNOME/glibmm/blob/master/configure.ac#L140

**Comment by hfiguiere** [comment]
This problem is more complex. You need to make sure the public interface stay ABI stable when you really mean it. 

What I would do is:
make the .pc file versionned. ie put the version in its time, in the present case "-0.9". This set the API for which the library client (in that case builder) would check to compile against.
But then the maitainer needs to ensure that the ABI isn't broken in minor updates. 

When API change, change the .pc file version. This is how most library do.

**Comment by albfan** [comment]
Makes sense. I will implement that way

**Comment by albfan** [comment]
@hfiguiere I have version number on pc file for pkg-config. I didn't do the same for la and so files yet (I need to do that too right?)

**Comment by albfan** [comment]
gnome-builder will not reuse nemiver to implement its debugger
